[package]
name = "opal"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
chrono = "0.4"
clap = "2.33"
env_logger = "0.9"
log = "0.4"
openssl = "0.10"
percent-encoding = "2.1"
url = "2.2"
